[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dwdi_programs = "HcuMHMV2iySZmGGGNvtZYaDGF1W2hJPuDzkWKajMrhJx"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "https://devnet.helius-rpc.com/?api-key=9fa77c10-9270-44c2-8363-c4305a98c81d"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run vitest run --test-timeout=50000"
initialize = "esrun --tsconfig=./tsconfig.json migrations/initializeProgram.ts"
updateFee = "esrun --tsconfig=./tsconfig.json migrations/updateProtocolFee.ts"
